In [1]:
import pandas as pd # 将pandas导入为pd
import numpy  as np # 将numpy导入为np
nums = [1, 2, 3, 4,5]
s = pd.Series(nums)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
nums = [1, 2, 3, 4, 5]
s = pd.Series(nums, index=[1, 2, 3, 4, 5])
print(s)

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [3]:
fruits = ['Orange','Banana','Mango']
fruits = pd.Series(fruits, index=[1, 2, 3])
print(fruits)

1    Orange
2    Banana
3     Mango
dtype: object

In [4]:
dct = {'name':'Asabeneh','country':'Finland','city':'Helsinki'}

In [5]:
s = pd.Series(dct)
print(s)

name       Asabeneh
country     Finland
city       Helsinki
dtype: object

In [6]:
s = pd.Series(np.linspace(5, 20, 10)) # linspace(起始点, 终点, 项目数)
print(s)

0     5.000000
1     6.666667
2     8.333333
3    10.000000
4    11.666667
5    13.333333
6    15.000000
7    16.666667
8    18.333333
9    20.000000
dtype: float64

In [7]:
data = [
    ['Asabeneh', 'Finland', 'Helsinki'], 
    ['David', 'UK', 'London'],
    ['John', 'Sweden', 'Stockholm']
]
df = pd.DataFrame(data, columns=['Name', 'Country', 'City'])
print(df)

       Name  Country       City
0  Asabeneh  Finland   Helsinki
1     David       UK     London
2      John   Sweden  Stockholm

In [9]:
# import pandas as pd
# 
# df = pd.read_csv('./data/weight-height.csv')
# print(df.head()) # 默认为前五行
# print(df.tail()) # 最后五行
# print(df.shape) # 行和列的数量
# print(df.columns) # 列名
# print(df.head(10)) # 前10行
# print(df.tail(10)) # 最后10行
# print(df['Gender'].value_counts()) # 计算每个值有多少个
# print(df.describe()) # 数据统计概要

In [8]:
# 导入pandas包
import pandas as pd
# 导入numpy包
import numpy as np
# 数据
data = [
    {"Name": "张三", "Country":"中国", "City":"上海"},
    {"Name": "李四", "Country":"中国", "City":"北京"},
    {"Name": "王五", "Country":"中国", "City":"广州"}]
# 创建一个数据框
df = pd.DataFrame(data)
print(df)

  Name Country City
0   张三      中国   上海
1   李四      中国   北京
2   王五      中国   广州

In [10]:
weights = [74, 78, 69]
df['Weight'] = weights
df

  Name Country City  Weight
0   张三      中国   上海      74
1   李四      中国   北京      78
2   王五      中国   广州      69

In [11]:
heights = [173, 175, 169]
df['Height'] = heights
df

  Name Country City  Weight  Height
0   张三      中国   上海      74     173
1   李四      中国   北京      78     175
2   王五      中国   广州      69     169

In [12]:
df['Name'] = ['赵六', '钱七', '孙八']
df

  Name Country City  Weight  Height
0   赵六      中国   上海      74     173
1   钱七      中国   北京      78     175
2   孙八      中国   广州      69     169

In [13]:
df.loc[1, 'Name'] = '小七'
df

  Name Country City  Weight  Height
0   赵六      中国   上海      74     173
1   小七      中国   北京      78     175
2   孙八      中国   广州      69     169

In [14]:
print('原始数据：\n', df)
df.iloc[1, 0] = '阿七'
print('修改后的数据：\n', df)

原始数据：
   Name Country City  Weight  Height
0   赵六      中国   上海      74     173
1   小七      中国   北京      78     175
2   孙八      中国   广州      69     169
修改后的数据：
   Name Country City  Weight  Height
0   赵六      中国   上海      74     173
1   阿七      中国   北京      78     175
2   孙八      中国   广州      69     169

In [15]:
# 添加身高、体重和BMI列
df['BMI'] = np.round(df['Weight'] / ((df['Height'] * 0.01) ** 2), 2) # 保留两位小数

print(df)

  Name Country City  Weight  Height    BMI
0   赵六      中国   上海      74     173  24.73
1   阿七      中国   北京      78     175  25.47
2   孙八      中国   广州      69     169  24.16

In [16]:
print(df.dtypes)

Name        object
Country     object
City        object
Weight       int64
Height       int64
BMI        float64
dtype: object

In [17]:
# 创建一个数据框
df = pd.DataFrame({
    'name': ['张三', '李四', '王五', '赵六'],
    'country': ['中国', '美国', '英国', '西班牙'],
    'age': [25, 15, 22, 28],
    '在职': [True, False, True, False]
})

print(df)

  name country  age     在职
0   张三      中国   25   True
1   李四      美国   15  False
2   王五      英国   22   True
3   赵六     西班牙   28  False

In [18]:
print(df[(df['age'] > 20) & (df['在职'] == True)])

  name country  age    在职
0   张三      中国   25  True
2   王五      英国   22  True